apiVersion: v1
kind: Service
metadata:
  name: redis
  labesl:
    name: redis-service
    app: voting-app 
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: voting-app
  
